version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=trnu(=iah2xlr#*lwwsp!tvyzjq!watrj=hi=kdmcmf8$$@_r$$m
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=<pk_test_your_publishable_key_here>
      - STRIPE_TEST_SECRET_KEY=<sk_test_your_secret_key_here>

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
