# Generated by Django 3.0 on 2020-01-09 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_revire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revire',
            new_name='Review',
        ),
    ]
